import { Open_Sans, Onest } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/page";
import Footer from "@/components/Footer/page";
import { Toaster } from "react-hot-toast";
const onest = Onest({ subsets: ["latin"] });
const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Enworit",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="../assets/favico.png" />
      </head>
      <body className={onest.className}>
        <main>
          {children}
          <Toaster />
        </main>
      </body>
    </html>
  )
}