import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/page";
import Footer from "@/components/Footer/page";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Enworit",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="../assets/favicon.ico" />
      </head>
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Footer/>

      </body>
    </html>
  )
}